### ISSUE TITLE
Questions about experiments related to mlp and softmax

### ISSUE THREAD

**Issue by redevaaa** [iesl/diora#3]
Hi, Thank you for your awesome paper and related codes.

I am trying to reproduce the experiments in your paper but have some trouble.
In the train.py, the parser excludes mlp and softmax.
`parser.add_argument('--arch', default='treelstm', choices=('treelstm',))
  parser.add_argument('--reconstruct_mode', default='margin', choices=('margin',))
`
Even if I add those parameters, when I run the training hyperparams like below,

`python -m torch.distributed.launch --nproc_per_node=$NGPUS diora/scripts/train.py \
  --arch mlp-shared \
  --batch_size 128 \
  --data_type nli \
  --elmo_cache_dir /home/hongry/data/elmo \ 
  --emb elmo \
  --hidden_dim 400 \
  --k_neg 100 \
  --log_every_batch 100 \
  --lr 2e-3 \
  --normalize unit \
  --reconstruct_mode softmax    
 --save_after 1000 --train_filter_length 20 \--train_path /home/hongry/data/allnli.jsonl --cuda --multigpu
`

error occurred like below,

`
Failed with shape: torch.Size([64, 6])
AttributeError: 'NoneType' object has no attribute 'view'
`

I am quite confused about this error and look forward to your help. Thank you!

**Comment by mrdrozdov** [comment]
We've added support for the softmax flag.
