### ISSUE TITLE
About the method of using ELMo.

### ISSUE THREAD

**Issue by caijiong** [iesl/diora#6]
Hi, 
I think ELMo can provide us context-sensitive embeddings of the words in a sentence. 
During the reading of code, I find you use an insensitive  ELMo.
Why are you use this implementation?  Is it because running ELMo on every sentence is very time-consuming?  Have you tried the context-sensitive implementation?

**Comment by mrdrozdov** [comment]
The context-free nature of word embeddings (provided by the first layer of elmo, i.e. the convolutional character encoder) is a useful inductive bias for unsupervised parsing. The computation cost of full elmo wasn't a barrier for us. For strong (partially) supervised models that use contextual models you may consider Compound PCFG (Kim et al.), Parsing w/ Constituency Tests (Cao et al.), or Learning from Naturally Occurring Brackets (Shi et al.).
